import * as React from 'react';

declare const components: Record<string, React.ComponentType<any>> & {
  ResponsiveContainer: React.ComponentType<any>;
};

export default components;
export const ResponsiveContainer: React.ComponentType<any>;
export const LineChart: React.ComponentType<any>;
export const BarChart: React.ComponentType<any>;
export const AreaChart: React.ComponentType<any>;
export const PieChart: React.ComponentType<any>;
export const ComposedChart: React.ComponentType<any>;
export const RadarChart: React.ComponentType<any>;
export const Line: React.ComponentType<any>;
export const Bar: React.ComponentType<any>;
export const Area: React.ComponentType<any>;
export const Pie: React.ComponentType<any>;
export const Cell: React.ComponentType<any>;
export const Radar: React.ComponentType<any>;
export const XAxis: React.ComponentType<any>;
export const YAxis: React.ComponentType<any>;
export const ZAxis: React.ComponentType<any>;
export const PolarAngleAxis: React.ComponentType<any>;
export const PolarRadiusAxis: React.ComponentType<any>;
export const CartesianGrid: React.ComponentType<any>;
export const Tooltip: React.ComponentType<any>;
export const Legend: React.ComponentType<any>;
export const ReferenceLine: React.ComponentType<any>;
export const ReferenceArea: React.ComponentType<any>;
export const ReferenceDot: React.ComponentType<any>;
export const Brush: React.ComponentType<any>;
export const ScatterChart: React.ComponentType<any>;
export const Scatter: React.ComponentType<any>;
export const RadialBarChart: React.ComponentType<any>;
export const RadialBar: React.ComponentType<any>;
export const Treemap: React.ComponentType<any>;
export const FunnelChart: React.ComponentType<any>;
export const Funnel: React.ComponentType<any>;
export const Sankey: React.ComponentType<any>;
export const ErrorBar: React.ComponentType<any>;
export const TooltipWrapper: React.ComponentType<any>;
export const Surface: React.ComponentType<any>;
export const Customized: React.ComponentType<any>;
